#!/bin/sh
sudo su
dnf upgrade -y 
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
dnf install fish ufw neofetch gnome-tweaks util-linux-user htop flat-remix-theme inxi flameshot code -y
dnf group upgrade multimedia -y
systemctl disable --now firewalld
ufw enable
ufw default deny incoming
ufw default allow outgoing
exit
chsh -s /usr/bin/fish
